[package]
name = "lumen-browser"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lumen-engine = { path = "../lumen-engine" }
lumen-css = { path = "../lumen-css" }
lumen-html = { path = "../lumen-html" }
lumen-platform = { path = "../lumen-platform" }
boa_engine = "0.21"
cookie = "0.18.1"



[lints]
workspace = true

[dev-dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
