[package]
name = "lumen-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arboard = "3"
dirs = "6"
lumen-browser = { path = "../../crates/lumen-browser" }
lumen-css = { path = "../../crates/lumen-css" }
lumen-engine = { path = "../../crates/lumen-engine" }
lumen-gpu = { path = "../../crates/lumen-gpu" }
lumen-platform = { path = "../../crates/lumen-platform" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
softbuffer = "0.4"
winit = "0.30"

[lints]
workspace = true
