[package]
name = "lumen-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lumen-browser = { path = "../../crates/lumen-browser" }
lumen-engine = { path = "../../crates/lumen-engine" }
lumen-platform = { path = "../../crates/lumen-platform" }
softbuffer = "0.4"
winit = "0.30"

[lints]
workspace = true
