[package]
name = "lumen-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lumen-html = { path = "../lumen-html" }
lumen-css = { path = "../lumen-css" }
font8x8 = "0.3"
fontdue = "0.9"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp"] }

[lints]
workspace = true
